title: Ridgewood, Queens, NY, 11385.
description: This is the project for my first CSCI project, and this analyzes the neighborhood, and the clean energy analysis.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
